name: ope-client
channels:
  - conda-forge

dependencies:
  - python=3.10

  # core
  - pip

  # dev tools
  - pytest
  - black
  - ruff

  # pip packages (grpc etc.)
  - pip:
      - pytest
      - grpcio
      - grpcio-tools
      - protobuf
      - watchfiles