# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: claim.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'claim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63laim.proto\x12\x05\x63laim\"5\n\x10\x43laimNodeRequest\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\x12\x11\n\tsessionId\x18\x02 \x01(\t\"E\n\x11\x43laimNodeResponse\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"7\n\x12ReleaseNodeRequest\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\x12\x11\n\tsessionId\x18\x02 \x01(\t\"G\n\x13ReleaseNodeResponse\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2\xaa\x01\n\x0c\x43laimService\x12I\n\x10StreamClaimNodes\x12\x17.claim.ClaimNodeRequest\x1a\x18.claim.ClaimNodeResponse(\x01\x30\x01\x12O\n\x12StreamReleaseNodes\x12\x19.claim.ReleaseNodeRequest\x1a\x1a.claim.ReleaseNodeResponse(\x01\x30\x01\x42\x19\xaa\x02\x16OPEDbEngine.gRPC.Claimb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'claim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\026OPEDbEngine.gRPC.Claim'
  _globals['_CLAIMNODEREQUEST']._serialized_start=22
  _globals['_CLAIMNODEREQUEST']._serialized_end=75
  _globals['_CLAIMNODERESPONSE']._serialized_start=77
  _globals['_CLAIMNODERESPONSE']._serialized_end=146
  _globals['_RELEASENODEREQUEST']._serialized_start=148
  _globals['_RELEASENODEREQUEST']._serialized_end=203
  _globals['_RELEASENODERESPONSE']._serialized_start=205
  _globals['_RELEASENODERESPONSE']._serialized_end=276
  _globals['_CLAIMSERVICE']._serialized_start=279
  _globals['_CLAIMSERVICE']._serialized_end=449
# @@protoc_insertion_point(module_scope)
