# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import work_pb2 as work__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in work_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSaveChanges = channel.stream_stream(
                '/work.WorkService/StreamSaveChanges',
                request_serializer=work__pb2.SaveNodeRequest.SerializeToString,
                response_deserializer=work__pb2.SaveNodeResponse.FromString,
                _registered_method=True)
        self.StreamGetWork = channel.unary_stream(
                '/work.WorkService/StreamGetWork',
                request_serializer=work__pb2.GetWorkRequest.SerializeToString,
                response_deserializer=work__pb2.GetWorkResponse.FromString,
                _registered_method=True)
        self.StreamNodeHistory = channel.unary_stream(
                '/work.WorkService/StreamNodeHistory',
                request_serializer=work__pb2.NodeHistoryRequest.SerializeToString,
                response_deserializer=work__pb2.NodeHistoryResponse.FromString,
                _registered_method=True)


class WorkServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamSaveChanges(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGetWork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamNodeHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSaveChanges': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSaveChanges,
                    request_deserializer=work__pb2.SaveNodeRequest.FromString,
                    response_serializer=work__pb2.SaveNodeResponse.SerializeToString,
            ),
            'StreamGetWork': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGetWork,
                    request_deserializer=work__pb2.GetWorkRequest.FromString,
                    response_serializer=work__pb2.GetWorkResponse.SerializeToString,
            ),
            'StreamNodeHistory': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamNodeHistory,
                    request_deserializer=work__pb2.NodeHistoryRequest.FromString,
                    response_serializer=work__pb2.NodeHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'work.WorkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('work.WorkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamSaveChanges(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/work.WorkService/StreamSaveChanges',
            work__pb2.SaveNodeRequest.SerializeToString,
            work__pb2.SaveNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGetWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/work.WorkService/StreamGetWork',
            work__pb2.GetWorkRequest.SerializeToString,
            work__pb2.GetWorkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamNodeHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/work.WorkService/StreamNodeHistory',
            work__pb2.NodeHistoryRequest.SerializeToString,
            work__pb2.NodeHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
