# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: work.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'work.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import node_pb2 as node__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nwork.proto\x12\x04work\x1a\nnode.proto\"\xb9\x01\n\x0fSaveNodeRequest\x12-\n\ncreateNode\x18\x01 \x01(\x0b\x32\x17.node.CreateNodeRequestH\x00\x12\x31\n\x0csetAttribute\x18\x02 \x01(\x0b\x32\x19.node.SetAttributeRequestH\x00\x12\x37\n\x0fremoveAttribute\x18\x03 \x01(\x0b\x32\x1c.node.RemoveAttributeRequestH\x00\x42\x0b\n\toperation\"W\n\x10SaveNodeResponse\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\tversionId\x18\x04 \x01(\t\" \n\x0eGetWorkRequest\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\"a\n\x0fGetWorkResponse\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\x12\x11\n\tversionId\x18\x02 \x01(\t\x12+\n\nattributes\x18\x03 \x03(\x0b\x32\x17.work.AttributeSnapshot\"B\n\x11\x41ttributeSnapshot\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x11\n\tvalueType\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\t\"$\n\x12NodeHistoryRequest\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\"\xa4\x01\n\x13NodeHistoryResponse\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\x12\x11\n\tversionId\x18\x02 \x01(\t\x12\x17\n\x0fparentVersionId\x18\x03 \x01(\t\x12\x11\n\tsessionId\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12+\n\nattributes\x18\x06 \x03(\x0b\x32\x17.work.AttributeSnapshot2\xe1\x01\n\x0bWorkService\x12\x46\n\x11StreamSaveChanges\x12\x15.work.SaveNodeRequest\x1a\x16.work.SaveNodeResponse(\x01\x30\x01\x12>\n\rStreamGetWork\x12\x14.work.GetWorkRequest\x1a\x15.work.GetWorkResponse0\x01\x12J\n\x11StreamNodeHistory\x12\x18.work.NodeHistoryRequest\x1a\x19.work.NodeHistoryResponse0\x01\x42\x18\xaa\x02\x15OPEDbEngine.gRPC.Workb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'work_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\025OPEDbEngine.gRPC.Work'
  _globals['_SAVENODEREQUEST']._serialized_start=33
  _globals['_SAVENODEREQUEST']._serialized_end=218
  _globals['_SAVENODERESPONSE']._serialized_start=220
  _globals['_SAVENODERESPONSE']._serialized_end=307
  _globals['_GETWORKREQUEST']._serialized_start=309
  _globals['_GETWORKREQUEST']._serialized_end=341
  _globals['_GETWORKRESPONSE']._serialized_start=343
  _globals['_GETWORKRESPONSE']._serialized_end=440
  _globals['_ATTRIBUTESNAPSHOT']._serialized_start=442
  _globals['_ATTRIBUTESNAPSHOT']._serialized_end=508
  _globals['_NODEHISTORYREQUEST']._serialized_start=510
  _globals['_NODEHISTORYREQUEST']._serialized_end=546
  _globals['_NODEHISTORYRESPONSE']._serialized_start=549
  _globals['_NODEHISTORYRESPONSE']._serialized_end=713
  _globals['_WORKSERVICE']._serialized_start=716
  _globals['_WORKSERVICE']._serialized_end=941
# @@protoc_insertion_point(module_scope)
