# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from Protos import claim_pb2 as Protos_dot_claim__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Protos/claim_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClaimServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamClaimNodes = channel.stream_stream(
                '/claim.ClaimService/StreamClaimNodes',
                request_serializer=Protos_dot_claim__pb2.ClaimNodeRequest.SerializeToString,
                response_deserializer=Protos_dot_claim__pb2.ClaimNodeResponse.FromString,
                _registered_method=True)
        self.StreamReleaseNodes = channel.stream_stream(
                '/claim.ClaimService/StreamReleaseNodes',
                request_serializer=Protos_dot_claim__pb2.ReleaseNodeRequest.SerializeToString,
                response_deserializer=Protos_dot_claim__pb2.ReleaseNodeResponse.FromString,
                _registered_method=True)


class ClaimServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamClaimNodes(self, request_iterator, context):
        """✅ Stream CLAIM multiple nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamReleaseNodes(self, request_iterator, context):
        """✅ Stream UNCLAIM multiple nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClaimServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamClaimNodes': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamClaimNodes,
                    request_deserializer=Protos_dot_claim__pb2.ClaimNodeRequest.FromString,
                    response_serializer=Protos_dot_claim__pb2.ClaimNodeResponse.SerializeToString,
            ),
            'StreamReleaseNodes': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamReleaseNodes,
                    request_deserializer=Protos_dot_claim__pb2.ReleaseNodeRequest.FromString,
                    response_serializer=Protos_dot_claim__pb2.ReleaseNodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'claim.ClaimService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('claim.ClaimService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClaimService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamClaimNodes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/claim.ClaimService/StreamClaimNodes',
            Protos_dot_claim__pb2.ClaimNodeRequest.SerializeToString,
            Protos_dot_claim__pb2.ClaimNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamReleaseNodes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/claim.ClaimService/StreamReleaseNodes',
            Protos_dot_claim__pb2.ReleaseNodeRequest.SerializeToString,
            Protos_dot_claim__pb2.ReleaseNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
