# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from Protos import node_pb2 as Protos_dot_node__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Protos/node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub:
    """✅ MAIN SERVICE
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNode = channel.unary_unary(
                '/node.NodeService/CreateNode',
                request_serializer=Protos_dot_node__pb2.CreateNodeRequest.SerializeToString,
                response_deserializer=Protos_dot_node__pb2.CreateNodeResponse.FromString,
                _registered_method=True)
        self.ClaimNode = channel.unary_unary(
                '/node.NodeService/ClaimNode',
                request_serializer=Protos_dot_node__pb2.ClaimNodeRequest.SerializeToString,
                response_deserializer=Protos_dot_node__pb2.ClaimNodeResponse.FromString,
                _registered_method=True)
        self.SetAttribute = channel.unary_unary(
                '/node.NodeService/SetAttribute',
                request_serializer=Protos_dot_node__pb2.SetAttributeRequest.SerializeToString,
                response_deserializer=Protos_dot_node__pb2.SetAttributeResponse.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/node.NodeService/GetNode',
                request_serializer=Protos_dot_node__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=Protos_dot_node__pb2.NodeResponse.FromString,
                _registered_method=True)
        self.StoreValue = channel.unary_unary(
                '/node.NodeService/StoreValue',
                request_serializer=Protos_dot_node__pb2.StoreValueRequest.SerializeToString,
                response_deserializer=Protos_dot_node__pb2.StoreValueResponse.FromString,
                _registered_method=True)
        self.RemoveAttribute = channel.unary_unary(
                '/node.NodeService/RemoveAttribute',
                request_serializer=Protos_dot_node__pb2.RemoveAttributeRequest.SerializeToString,
                response_deserializer=Protos_dot_node__pb2.RemoveAttributeResponse.FromString,
                _registered_method=True)
        self.BulkSetAttributes = channel.unary_unary(
                '/node.NodeService/BulkSetAttributes',
                request_serializer=Protos_dot_node__pb2.BulkSetAttributesRequest.SerializeToString,
                response_deserializer=Protos_dot_node__pb2.BulkSetAttributesResponse.FromString,
                _registered_method=True)
        self.BulkRemoveAttributes = channel.unary_unary(
                '/node.NodeService/BulkRemoveAttributes',
                request_serializer=Protos_dot_node__pb2.BulkRemoveAttributesRequest.SerializeToString,
                response_deserializer=Protos_dot_node__pb2.BulkRemoveAttributesResponse.FromString,
                _registered_method=True)


class NodeServiceServicer:
    """✅ MAIN SERVICE
    """

    def CreateNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkSetAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkRemoveAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNode': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNode,
                    request_deserializer=Protos_dot_node__pb2.CreateNodeRequest.FromString,
                    response_serializer=Protos_dot_node__pb2.CreateNodeResponse.SerializeToString,
            ),
            'ClaimNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimNode,
                    request_deserializer=Protos_dot_node__pb2.ClaimNodeRequest.FromString,
                    response_serializer=Protos_dot_node__pb2.ClaimNodeResponse.SerializeToString,
            ),
            'SetAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAttribute,
                    request_deserializer=Protos_dot_node__pb2.SetAttributeRequest.FromString,
                    response_serializer=Protos_dot_node__pb2.SetAttributeResponse.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=Protos_dot_node__pb2.GetNodeRequest.FromString,
                    response_serializer=Protos_dot_node__pb2.NodeResponse.SerializeToString,
            ),
            'StoreValue': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreValue,
                    request_deserializer=Protos_dot_node__pb2.StoreValueRequest.FromString,
                    response_serializer=Protos_dot_node__pb2.StoreValueResponse.SerializeToString,
            ),
            'RemoveAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAttribute,
                    request_deserializer=Protos_dot_node__pb2.RemoveAttributeRequest.FromString,
                    response_serializer=Protos_dot_node__pb2.RemoveAttributeResponse.SerializeToString,
            ),
            'BulkSetAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkSetAttributes,
                    request_deserializer=Protos_dot_node__pb2.BulkSetAttributesRequest.FromString,
                    response_serializer=Protos_dot_node__pb2.BulkSetAttributesResponse.SerializeToString,
            ),
            'BulkRemoveAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkRemoveAttributes,
                    request_deserializer=Protos_dot_node__pb2.BulkRemoveAttributesRequest.FromString,
                    response_serializer=Protos_dot_node__pb2.BulkRemoveAttributesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'node.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('node.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService:
    """✅ MAIN SERVICE
    """

    @staticmethod
    def CreateNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node.NodeService/CreateNode',
            Protos_dot_node__pb2.CreateNodeRequest.SerializeToString,
            Protos_dot_node__pb2.CreateNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node.NodeService/ClaimNode',
            Protos_dot_node__pb2.ClaimNodeRequest.SerializeToString,
            Protos_dot_node__pb2.ClaimNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node.NodeService/SetAttribute',
            Protos_dot_node__pb2.SetAttributeRequest.SerializeToString,
            Protos_dot_node__pb2.SetAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node.NodeService/GetNode',
            Protos_dot_node__pb2.GetNodeRequest.SerializeToString,
            Protos_dot_node__pb2.NodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node.NodeService/StoreValue',
            Protos_dot_node__pb2.StoreValueRequest.SerializeToString,
            Protos_dot_node__pb2.StoreValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node.NodeService/RemoveAttribute',
            Protos_dot_node__pb2.RemoveAttributeRequest.SerializeToString,
            Protos_dot_node__pb2.RemoveAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkSetAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node.NodeService/BulkSetAttributes',
            Protos_dot_node__pb2.BulkSetAttributesRequest.SerializeToString,
            Protos_dot_node__pb2.BulkSetAttributesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkRemoveAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node.NodeService/BulkRemoveAttributes',
            Protos_dot_node__pb2.BulkRemoveAttributesRequest.SerializeToString,
            Protos_dot_node__pb2.BulkRemoveAttributesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
