# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from Protos import session_pb2 as Protos_dot_session__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Protos/session_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSession = channel.unary_unary(
                '/session.SessionService/StartSession',
                request_serializer=Protos_dot_session__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=Protos_dot_session__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/session.SessionService/CloseSession',
                request_serializer=Protos_dot_session__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=Protos_dot_session__pb2.SessionActionResponse.FromString,
                _registered_method=True)
        self.AbortSession = channel.unary_unary(
                '/session.SessionService/AbortSession',
                request_serializer=Protos_dot_session__pb2.AbortSessionRequest.SerializeToString,
                response_deserializer=Protos_dot_session__pb2.SessionActionResponse.FromString,
                _registered_method=True)


class SessionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=Protos_dot_session__pb2.StartSessionRequest.FromString,
                    response_serializer=Protos_dot_session__pb2.StartSessionResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=Protos_dot_session__pb2.CloseSessionRequest.FromString,
                    response_serializer=Protos_dot_session__pb2.SessionActionResponse.SerializeToString,
            ),
            'AbortSession': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortSession,
                    request_deserializer=Protos_dot_session__pb2.AbortSessionRequest.FromString,
                    response_serializer=Protos_dot_session__pb2.SessionActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'session.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('session.SessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/session.SessionService/StartSession',
            Protos_dot_session__pb2.StartSessionRequest.SerializeToString,
            Protos_dot_session__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/session.SessionService/CloseSession',
            Protos_dot_session__pb2.CloseSessionRequest.SerializeToString,
            Protos_dot_session__pb2.SessionActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/session.SessionService/AbortSession',
            Protos_dot_session__pb2.AbortSessionRequest.SerializeToString,
            Protos_dot_session__pb2.SessionActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
