# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protos/session.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'Protos/session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14Protos/session.proto\x12\x07session\"%\n\x13StartSessionRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\"^\n\x14StartSessionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tsessionId\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\terrorCode\x18\x04 \x01(\t\"(\n\x13\x43loseSessionRequest\x12\x11\n\tsessionId\x18\x01 \x01(\t\"L\n\x15SessionActionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\terrorCode\x18\x03 \x01(\t2\xab\x01\n\x0eSessionService\x12K\n\x0cStartSession\x12\x1c.session.StartSessionRequest\x1a\x1d.session.StartSessionResponse\x12L\n\x0c\x43loseSession\x12\x1c.session.CloseSessionRequest\x1a\x1e.session.SessionActionResponseB\x1b\xaa\x02\x18OPEDbEngine.gRPC.Sessionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protos.session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\030OPEDbEngine.gRPC.Session'
  _globals['_STARTSESSIONREQUEST']._serialized_start=33
  _globals['_STARTSESSIONREQUEST']._serialized_end=70
  _globals['_STARTSESSIONRESPONSE']._serialized_start=72
  _globals['_STARTSESSIONRESPONSE']._serialized_end=166
  _globals['_CLOSESESSIONREQUEST']._serialized_start=168
  _globals['_CLOSESESSIONREQUEST']._serialized_end=208
  _globals['_SESSIONACTIONRESPONSE']._serialized_start=210
  _globals['_SESSIONACTIONRESPONSE']._serialized_end=286
  _globals['_SESSIONSERVICE']._serialized_start=289
  _globals['_SESSIONSERVICE']._serialized_end=460
# @@protoc_insertion_point(module_scope)
